### ISSUE TITLE
Crear reporte de puntuación del año de todo el cuartel

### ISSUE THREAD

**Issue by jdottori** [Unicen-Tupar/bomberos#185]
Reporte de puntuación anual, similar a la del "Puntuación" pero de un año (periodo) para todos los bomberos. No es un reporte actualmente.
- [ ] Pedir planilla de ejemplo
- [ ] Cambiar la de mes para que sea "fecha desde/hasta"
- [ ] Implementar (con TDD)
